name: Update Briefed Feed

on:
  schedule:
    # Runs every Monday at 06:00 UTC, which corresponds to 09:00 in Israel (Asia/Jerusalem) during standard time. Adjust if daylight savings changes.
    - cron: '0 6 * * 1'
    workflow_dispatch:
  permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run feed fetcher
        run: python briefed_site/fetch_feed.py
      - name: Commit and push changes
        run: |
          git config user.name "briefed-bot"
          git config user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then echo "No changes to commit"; else git commit -m "Automated feed update"; git push; fi
